# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shuup', '0027_modify_shop_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutableaddress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='street', blank=True),
        ),
        migrations.AlterField(
            model_name='mutableaddress',
            name='city',
            field=models.CharField(max_length=255, verbose_name='city', blank=True)
        ),
        migrations.AlterField(
            model_name='immutableaddress',
            name='street',
            field=models.CharField(max_length=255, verbose_name='street', blank=True),
        ),
        migrations.AlterField(
            model_name='immutableaddress',
            name='city',
            field=models.CharField(max_length=255, verbose_name='city', blank=True)
        )
    ]
